# -*- coding: utf-8 -*-
"""AAI03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vpe22wCKJyUyl3xee9RUoVAUkp3pcK7
"""

!pip install pgmpy

from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.factors.discrete import TabularCPD
from pgmpy.sampling import GibbsSampling
import networkx as nx
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

# Define Bayesian Network structure
alarm_model = DiscreteBayesianNetwork([
    ("Burglary", "Alarm"),
    ("Earthquake", "Alarm"),
    ("Alarm", "JohnCalls"),
    ("Alarm", "MaryCalls")
])

# Define CPTs
cpd_b = TabularCPD("Burglary", 2, [[0.999], [0.001]])
cpd_e = TabularCPD("Earthquake", 2, [[0.998], [0.002]])

cpd_a = TabularCPD(
    "Alarm", 2,
    [[0.999, 0.71, 0.06, 0.05],
     [0.001, 0.29, 0.94, 0.95]],
    evidence=["Burglary", "Earthquake"],
    evidence_card=[2, 2]
)

cpd_j = TabularCPD(
    "JohnCalls", 2,
    [[0.95, 0.1],
     [0.05, 0.9]],
    evidence=["Alarm"],
    evidence_card=[2]
)

cpd_m = TabularCPD(
    "MaryCalls", 2,
    [[0.99, 0.3],
     [0.01, 0.7]],
    evidence=["Alarm"],
    evidence_card=[2]
)

# Add CPTs and check model
alarm_model.add_cpds(cpd_b, cpd_e, cpd_a, cpd_j, cpd_m)
alarm_model.check_model()

# -------- Approximate Inference using Gibbs Sampling --------
gibbs_sampler = GibbsSampling(alarm_model)

num_samples = 50000
samples = gibbs_sampler.sample(size=num_samples)

# Estimate probability of Burglary given evidence
evidence_samples = samples[
    (samples["JohnCalls"] == 1) & (samples["MaryCalls"] == 1)
]

prob_burglary = evidence_samples["Burglary"].mean()

print("Approximate Inference using Gibbs Sampling")
print("P(Burglary | JohnCalls=1, MaryCalls=1) ≈", prob_burglary)

# -------- Draw Bayesian Network diagram --------
G = nx.DiGraph(alarm_model.edges())
plt.figure(figsize=(6,4))
nx.draw(G, with_labels=True, node_size=3000, node_color="lightblue", arrowsize=20)
plt.title("Alarm Bayesian Network")
plt.show()

